FROM rust:1.62.1-buster

# required by bingen
RUN apt-get update && \
	apt-get install -y \
		build-essential \
		cmake \
		clang \
		libclang-dev \
		llvm-dev \
		git && \
	apt-get clean

RUN rustup target add armv5te-unknown-linux-gnueabi
RUN rustup target add arm-unknown-linux-gnueabihf
RUN cargo install cargo-bitbake

RUN echo '[target.armv5te-unknown-linux-gnueabi]\n\
linker = "arm-linux-gnueabi-gcc"\n\
[target.arm-unknown-linux-gnueabihf]\n\
linker = "arm-linux-gnueabihf-gcc"\n'\
>> /usr/local/cargo/config

RUN mkdir -p /tmp
RUN cd /tmp && git clone https://github.com/seife/opkg-utils.git && cd /tmp/opkg-utils && PREFIX=/usr make install

ENV LLVM_CONFIG_PATH=llvm-config
ENV PROJECT_PATH=/chirpstack-udp-forwarder
RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH

COPY . /chirpstack-udp-forwarder
RUN cargo fetch
